name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  quality-gate:
    name: Quality Gate # required: it is part of the check name
    permissions:
      id-token: write # allow GitHub's OIDC provider to create a JSON Web Token
      contents: read
    uses: 24dlong/github-actions-library/.github/workflows/javascript-pull-request.yml@v7
