name: Merge Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write # for semantic-release to be able to publish a GitHub release
  issues: write # for semantic-release to be able to comment on released issues
  pull-requests: write # for semantic-release to be able to comment on released pull requests
  id-token: write # allow GitHub's OIDC provider to create a JSON Web Token

jobs:
  publish:
    uses: 24dlong/github-actions-library/.github/workflows/javascript-publish.yml@v7
