name: Merge Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write # for semantic-release to be able to publish a GitHub release
  issues: write # for semantic-release to be able to comment on released issues
  pull-requests: write # for semantic-release to be able to comment on released pull requests

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Publish Action
        uses: 24dlong/github-actions-library/actions/javascript/publish@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
