name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    name: Quality Gate
    steps:
      - uses: 24dlong/github-actions-library/actions/javascript/quality-gate@1.1.1
